# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "identify>=2.6.16",
# ]
# ///

from identify.identify import ALL_TAGS
from identify.interpreters import INTERPRETERS
from identify.extensions import EXTENSIONS, EXTENSIONS_NEED_BINARY_CHECK, NAMES


def gen():
    with open("src/tags.rs", "w", newline='\n') as f:
        f.write("// This file is auto-generated by gen.py. DO NOT EDIT MANUALLY.\n\n")
        f.write("pub const ALL_TAGS: phf::Set<&str> = phf::phf_set! {\n")
        for tag in sorted(ALL_TAGS):
            f.write(f'    "{tag}",\n')
        f.write("};\n\n")

        f.write("pub const INTERPRETERS: phf::Map<&str, &[&str]> = phf::phf_map! {\n")
        for interpreter, tags in INTERPRETERS.items():
            tags_str = ", ".join(f'"{tag}"' for tag in sorted(tags))
            f.write(f'    "{interpreter}" => &[{tags_str}],\n')
        f.write("};\n\n")

        EXTENSIONS.update(EXTENSIONS_NEED_BINARY_CHECK)
        f.write("pub const EXTENSIONS: phf::Map<&str, &[&str]> = phf::phf_map! {\n")
        for ext, tags in EXTENSIONS.items():
            tags_str = ", ".join(f'"{tag}"' for tag in sorted(tags))
            f.write(f'    "{ext}" => &[{tags_str}],\n')
        f.write("};\n\n")

        f.write("pub const NAMES: phf::Map<&str, &[&str]> = phf::phf_map! {\n")
        for name, tags in NAMES.items():
            tags_str = ", ".join(f'"{tag}"' for tag in sorted(tags))
            f.write(f'    "{name}" => &[{tags_str}],\n')
        f.write("};\n")

def main():
    gen()


if __name__ == "__main__":
    main()
