// This file is auto-generated by gen.py. DO NOT EDIT MANUALLY.

use crate::TagSet;

pub const ALL_TAGS: [&str; 312] = [
    "adobe-illustrator",
    "alpm",
    "apinotes",
    "asar",
    "asciidoc",
    "ash",
    "asm",
    "aspectj",
    "astro",
    "audio",
    "avif",
    "avro-schema",
    "awk",
    "babelrc",
    "bash",
    "batch",
    "bats",
    "bazel",
    "bazelrc",
    "beancount",
    "bib",
    "binary",
    "bitbake",
    "bitmap",
    "bowerrc",
    "browserslistrc",
    "bzip2",
    "bzip3",
    "c",
    "c#",
    "c#script",
    "c++",
    "c2hs",
    "cargo",
    "cargo-lock",
    "cbsd",
    "clojure",
    "clojurescript",
    "cmake",
    "codespellrc",
    "coffee",
    "coveragerc",
    "crystal",
    "csh",
    "cson",
    "csproj",
    "css",
    "csslintrc",
    "csv",
    "cuda",
    "cue",
    "cylc",
    "cython",
    "dart",
    "dash",
    "dbc",
    "def",
    "diff",
    "directory",
    "dockerfile",
    "dockerignore",
    "dotenv",
    "dtd",
    "editorconfig",
    "edn",
    "ejs",
    "ejson",
    "elixir",
    "elm",
    "entitlements",
    "eot",
    "eps",
    "erb",
    "erlang",
    "executable",
    "expect",
    "f#",
    "f#script",
    "file",
    "fish",
    "fits",
    "flake8",
    "fortran",
    "fsproj",
    "gdscript",
    "geojson",
    "ggb",
    "gherkin",
    "gif",
    "gitattributes",
    "gitconfig",
    "gitignore",
    "gitlint",
    "gitmodules",
    "gleam",
    "go",
    "go-mod",
    "go-sum",
    "gotmpl",
    "gpx",
    "graphql",
    "groovy",
    "gyb",
    "gyp",
    "gzip",
    "handlebars",
    "haskell",
    "hcl",
    "header",
    "hgrc",
    "hlsl",
    "html",
    "icalendar",
    "icns",
    "icon",
    "idl",
    "idris",
    "image",
    "inc",
    "ini",
    "inl",
    "ino",
    "inx",
    "ipxe",
    "isort",
    "jade",
    "jar",
    "java",
    "java-properties",
    "javascript",
    "jbuilder",
    "jenkins",
    "jinja",
    "jpeg",
    "jshintrc",
    "json",
    "json5",
    "jsonc",
    "jsonld",
    "jsonnet",
    "jsx",
    "julia",
    "jupyter",
    "kml",
    "kotlin",
    "ksh",
    "lazarus",
    "lazarus-form",
    "lean",
    "lektor",
    "lektorproject",
    "less",
    "liquid",
    "literate-haskell",
    "lua",
    "m4",
    "magik",
    "mailmap",
    "makefile",
    "manifest",
    "map",
    "markdown",
    "mdx",
    "mention-bot",
    "meson",
    "meson-options",
    "metal",
    "mib",
    "modulemap",
    "msbuild",
    "musescore",
    "mustache",
    "myst",
    "ngdoc",
    "nim",
    "nimble",
    "nix",
    "non-executable",
    "npmignore",
    "nunjucks",
    "objective-c",
    "objective-c++",
    "ocaml",
    "otf",
    "p12",
    "pascal",
    "pdbrc",
    "pdf",
    "pem",
    "perl",
    "php",
    "php7",
    "php8",
    "piskel",
    "pkgbuild",
    "plain-text",
    "plantuml",
    "plist",
    "png",
    "pofile",
    "pom",
    "powershell",
    "ppm",
    "prettierignore",
    "prisma",
    "proto",
    "pug",
    "puppet",
    "purescript",
    "pyi",
    "pylintrc",
    "pypirc",
    "pyproj",
    "pyproject",
    "python",
    "python2",
    "python3",
    "pyz",
    "qml",
    "r",
    "relax-ng",
    "resx",
    "robot",
    "rst",
    "ruby",
    "rust",
    "salt",
    "salt-lint",
    "sas",
    "sass",
    "sbt",
    "scala",
    "scheme",
    "scons",
    "scss",
    "sh",
    "shell",
    "sln",
    "slnx",
    "socket",
    "solidity",
    "spec",
    "sql",
    "stylus",
    "svelte",
    "svg",
    "swf",
    "swift",
    "swiftdeps",
    "symlink",
    "system-verilog",
    "tar",
    "tcsh",
    "templ",
    "terraform",
    "tex",
    "text",
    "textproto",
    "thrift",
    "tiff",
    "tiltfile",
    "toml",
    "ts",
    "tsv",
    "tsx",
    "ttf",
    "twig",
    "twisted",
    "txsprofile",
    "urdf",
    "vb",
    "vbproj",
    "vcxproj",
    "vdx",
    "verilog",
    "vhdl",
    "vim",
    "vtl",
    "vue",
    "wav",
    "webp",
    "wheel",
    "wkt",
    "woff",
    "woff2",
    "wsdl",
    "wsgi",
    "xacro",
    "xaml",
    "xcconfig",
    "xcodebuild",
    "xcprivacy",
    "xcscheme",
    "xcsettings",
    "xctestplan",
    "xcworkspacedata",
    "xhtml",
    "xliff",
    "xml",
    "xquery",
    "xsd",
    "xsl",
    "yaml",
    "yamlld",
    "yamllint",
    "yang",
    "yin",
    "zcml",
    "zig",
    "zip",
    "zpt",
    "zsh",
];

pub const TAG_FILE: u16 = 78;
pub const TAG_DIRECTORY: u16 = 58;
pub const TAG_SYMLINK: u16 = 249;
pub const TAG_SOCKET: u16 = 239;
pub const TAG_EXECUTABLE: u16 = 74;
pub const TAG_NON_EXECUTABLE: u16 = 177;
pub const TAG_TEXT: u16 = 256;
pub const TAG_BINARY: u16 = 21;

pub const TAG_SET_FILE: TagSet = TagSet::new(&[78]);
pub const TAG_SET_DIRECTORY: TagSet = TagSet::new(&[58]);
pub const TAG_SET_SYMLINK: TagSet = TagSet::new(&[249]);
pub const TAG_SET_SOCKET: TagSet = TagSet::new(&[239]);
pub const TAG_SET_TEXT: TagSet = TagSet::new(&[256]);
pub const TAG_SET_TEXT_OR_BINARY: TagSet = TagSet::new(&[21, 256]);
pub const TAG_SET_EXECUTABLE_TEXT: TagSet = TagSet::new(&[74, 256]);
pub const TAG_SET_JSON: TagSet = TagSet::new(&[135]);
pub const TAG_SET_JSON5: TagSet = TagSet::new(&[136]);
pub const TAG_SET_JSONC: TagSet = TagSet::new(&[137]);
pub const TAG_SET_TOML: TagSet = TagSet::new(&[261]);
pub const TAG_SET_XML: TagSet = TagSet::new(&[298]);
pub const TAG_SET_YAML: TagSet = TagSet::new(&[302]);

pub const INTERPRETERS: phf::Map<&str, TagSet> = phf::phf_map! {
    // ["ash", "shell"]
    "ash" => TagSet::new(&[5, 236]),
    // ["awk"]
    "awk" => TagSet::new(&[12]),
    // ["bash", "shell"]
    "bash" => TagSet::new(&[14, 236]),
    // ["bash", "bats", "shell"]
    "bats" => TagSet::new(&[14, 16, 236]),
    // ["cbsd", "shell"]
    "cbsd" => TagSet::new(&[35, 236]),
    // ["csh", "shell"]
    "csh" => TagSet::new(&[43, 236]),
    // ["dash", "shell"]
    "dash" => TagSet::new(&[54, 236]),
    // ["erlang"]
    "escript" => TagSet::new(&[73]),
    // ["expect"]
    "expect" => TagSet::new(&[75]),
    // ["ksh", "shell"]
    "ksh" => TagSet::new(&[145, 236]),
    // ["javascript"]
    "node" => TagSet::new(&[129]),
    // ["javascript"]
    "nodejs" => TagSet::new(&[129]),
    // ["perl"]
    "perl" => TagSet::new(&[189]),
    // ["php"]
    "php" => TagSet::new(&[190]),
    // ["php", "php7"]
    "php7" => TagSet::new(&[190, 191]),
    // ["php", "php8"]
    "php8" => TagSet::new(&[190, 192]),
    // ["python"]
    "python" => TagSet::new(&[214]),
    // ["python", "python2"]
    "python2" => TagSet::new(&[214, 215]),
    // ["python", "python3"]
    "python3" => TagSet::new(&[214, 216]),
    // ["ruby"]
    "ruby" => TagSet::new(&[224]),
    // ["sh", "shell"]
    "sh" => TagSet::new(&[235, 236]),
    // ["shell", "tcsh"]
    "tcsh" => TagSet::new(&[236, 252]),
    // ["shell", "zsh"]
    "zsh" => TagSet::new(&[236, 311]),
};

pub const EXTENSIONS: phf::Map<&str, TagSet> = phf::phf_map! {
    // ["asciidoc", "text"]
    "adoc" => TagSet::new(&[4, 256]),
    // ["adobe-illustrator", "binary"]
    "ai" => TagSet::new(&[0, 21]),
    // ["aspectj", "text"]
    "aj" => TagSet::new(&[7, 256]),
    // ["apinotes", "text"]
    "apinotes" => TagSet::new(&[2, 256]),
    // ["asar", "binary"]
    "asar" => TagSet::new(&[3, 21]),
    // ["asciidoc", "text"]
    "asciidoc" => TagSet::new(&[4, 256]),
    // ["asm", "text"]
    "asm" => TagSet::new(&[6, 256]),
    // ["astro", "text"]
    "astro" => TagSet::new(&[8, 256]),
    // ["avif", "binary", "image"]
    "avif" => TagSet::new(&[10, 21, 117]),
    // ["avro-schema", "text"]
    "avsc" => TagSet::new(&[11, 256]),
    // ["bash", "shell", "text"]
    "bash" => TagSet::new(&[14, 236, 256]),
    // ["batch", "text"]
    "bat" => TagSet::new(&[15, 256]),
    // ["bash", "bats", "shell", "text"]
    "bats" => TagSet::new(&[14, 16, 236, 256]),
    // ["bazel", "text"]
    "bazel" => TagSet::new(&[17, 256]),
    // ["bitbake", "text"]
    "bb" => TagSet::new(&[22, 256]),
    // ["bitbake", "text"]
    "bbappend" => TagSet::new(&[22, 256]),
    // ["bitbake", "text"]
    "bbclass" => TagSet::new(&[22, 256]),
    // ["beancount", "text"]
    "beancount" => TagSet::new(&[19, 256]),
    // ["bib", "text"]
    "bib" => TagSet::new(&[20, 256]),
    // ["binary", "bitmap", "image"]
    "bmp" => TagSet::new(&[21, 23, 117]),
    // ["binary", "bzip2"]
    "bz2" => TagSet::new(&[21, 26]),
    // ["binary", "bzip3"]
    "bz3" => TagSet::new(&[21, 27]),
    // ["bazel", "text"]
    "bzl" => TagSet::new(&[17, 256]),
    // ["c", "text"]
    "c" => TagSet::new(&[28, 256]),
    // ["c++", "text"]
    "c++" => TagSet::new(&[31, 256]),
    // ["c++", "text"]
    "c++m" => TagSet::new(&[31, 256]),
    // ["c++", "text"]
    "cc" => TagSet::new(&[31, 256]),
    // ["c++", "text"]
    "ccm" => TagSet::new(&[31, 256]),
    // ["text"]
    "cfg" => TagSet::new(&[256]),
    // ["c2hs", "text"]
    "chs" => TagSet::new(&[32, 256]),
    // ["javascript", "text"]
    "cjs" => TagSet::new(&[129, 256]),
    // ["clojure", "text"]
    "clj" => TagSet::new(&[36, 256]),
    // ["clojure", "text"]
    "cljc" => TagSet::new(&[36, 256]),
    // ["clojure", "clojurescript", "text"]
    "cljs" => TagSet::new(&[36, 37, 256]),
    // ["cmake", "text"]
    "cmake" => TagSet::new(&[38, 256]),
    // ["batch", "text"]
    "cmd" => TagSet::new(&[15, 256]),
    // ["text"]
    "cnf" => TagSet::new(&[256]),
    // ["coffee", "text"]
    "coffee" => TagSet::new(&[40, 256]),
    // ["text"]
    "conf" => TagSet::new(&[256]),
    // ["c++", "text"]
    "cpp" => TagSet::new(&[31, 256]),
    // ["c++", "text"]
    "cppm" => TagSet::new(&[31, 256]),
    // ["crystal", "text"]
    "cr" => TagSet::new(&[42, 256]),
    // ["pem", "text"]
    "crt" => TagSet::new(&[188, 256]),
    // ["c#", "text"]
    "cs" => TagSet::new(&[29, 256]),
    // ["csh", "shell", "text"]
    "csh" => TagSet::new(&[43, 236, 256]),
    // ["cson", "text"]
    "cson" => TagSet::new(&[44, 256]),
    // ["csproj", "msbuild", "text", "xml"]
    "csproj" => TagSet::new(&[45, 169, 256, 298]),
    // ["css", "text"]
    "css" => TagSet::new(&[46, 256]),
    // ["csv", "text"]
    "csv" => TagSet::new(&[48, 256]),
    // ["c#", "c#script", "text"]
    "csx" => TagSet::new(&[29, 30, 256]),
    // ["text", "ts"]
    "cts" => TagSet::new(&[256, 262]),
    // ["cuda", "text"]
    "cu" => TagSet::new(&[49, 256]),
    // ["cue", "text"]
    "cue" => TagSet::new(&[50, 256]),
    // ["cuda", "text"]
    "cuh" => TagSet::new(&[49, 256]),
    // ["c++", "text"]
    "cxx" => TagSet::new(&[31, 256]),
    // ["c++", "text"]
    "cxxm" => TagSet::new(&[31, 256]),
    // ["cylc", "text"]
    "cylc" => TagSet::new(&[51, 256]),
    // ["dart", "text"]
    "dart" => TagSet::new(&[53, 256]),
    // ["dbc", "text"]
    "dbc" => TagSet::new(&[55, 256]),
    // ["def", "text"]
    "def" => TagSet::new(&[56, 256]),
    // ["diff", "text"]
    "diff" => TagSet::new(&[57, 256]),
    // ["binary"]
    "dll" => TagSet::new(&[21]),
    // ["dtd", "text"]
    "dtd" => TagSet::new(&[62, 256]),
    // ["binary", "jar", "zip"]
    "ear" => TagSet::new(&[21, 126, 309]),
    // ["clojure", "edn", "text"]
    "edn" => TagSet::new(&[36, 64, 256]),
    // ["ejs", "text"]
    "ejs" => TagSet::new(&[65, 256]),
    // ["ejson", "json", "text"]
    "ejson" => TagSet::new(&[66, 135, 256]),
    // ["elm", "text"]
    "elm" => TagSet::new(&[68, 256]),
    // ["entitlements", "plist"]
    "entitlements" => TagSet::new(&[69, 197]),
    // ["dotenv", "text"]
    "env" => TagSet::new(&[61, 256]),
    // ["binary", "eot"]
    "eot" => TagSet::new(&[21, 70]),
    // ["binary", "eps"]
    "eps" => TagSet::new(&[21, 71]),
    // ["erb", "text"]
    "erb" => TagSet::new(&[72, 256]),
    // ["erlang", "text"]
    "erl" => TagSet::new(&[73, 256]),
    // ["erlang", "text"]
    "escript" => TagSet::new(&[73, 256]),
    // ["elixir", "text"]
    "ex" => TagSet::new(&[67, 256]),
    // ["binary"]
    "exe" => TagSet::new(&[21]),
    // ["elixir", "text"]
    "exs" => TagSet::new(&[67, 256]),
    // ["text", "yaml"]
    "eyaml" => TagSet::new(&[256, 302]),
    // ["fortran", "text"]
    "f03" => TagSet::new(&[82, 256]),
    // ["fortran", "text"]
    "f08" => TagSet::new(&[82, 256]),
    // ["fortran", "text"]
    "f90" => TagSet::new(&[82, 256]),
    // ["fortran", "text"]
    "f95" => TagSet::new(&[82, 256]),
    // ["gherkin", "text"]
    "feature" => TagSet::new(&[87, 256]),
    // ["fish", "text"]
    "fish" => TagSet::new(&[79, 256]),
    // ["binary", "fits"]
    "fits" => TagSet::new(&[21, 80]),
    // ["f#", "text"]
    "fs" => TagSet::new(&[76, 256]),
    // ["fsproj", "msbuild", "text", "xml"]
    "fsproj" => TagSet::new(&[83, 169, 256, 298]),
    // ["f#", "f#script", "text"]
    "fsx" => TagSet::new(&[76, 77, 256]),
    // ["gdscript", "text"]
    "gd" => TagSet::new(&[84, 256]),
    // ["ruby", "text"]
    "gemspec" => TagSet::new(&[224, 256]),
    // ["geojson", "json", "text"]
    "geojson" => TagSet::new(&[85, 135, 256]),
    // ["binary", "ggb", "zip"]
    "ggb" => TagSet::new(&[21, 86, 309]),
    // ["binary", "gif", "image"]
    "gif" => TagSet::new(&[21, 88, 117]),
    // ["gleam", "text"]
    "gleam" => TagSet::new(&[94, 256]),
    // ["go", "text"]
    "go" => TagSet::new(&[95, 256]),
    // ["gotmpl", "text"]
    "gotmpl" => TagSet::new(&[98, 256]),
    // ["gpx", "text", "xml"]
    "gpx" => TagSet::new(&[99, 256, 298]),
    // ["groovy", "text"]
    "gradle" => TagSet::new(&[101, 256]),
    // ["graphql", "text"]
    "graphql" => TagSet::new(&[100, 256]),
    // ["groovy", "text"]
    "groovy" => TagSet::new(&[101, 256]),
    // ["gyb", "text"]
    "gyb" => TagSet::new(&[102, 256]),
    // ["gyp", "python", "text"]
    "gyp" => TagSet::new(&[103, 214, 256]),
    // ["gyp", "python", "text"]
    "gypi" => TagSet::new(&[103, 214, 256]),
    // ["binary", "gzip"]
    "gz" => TagSet::new(&[21, 104]),
    // ["c", "c++", "header", "text"]
    "h" => TagSet::new(&[28, 31, 108, 256]),
    // ["handlebars", "text"]
    "hbs" => TagSet::new(&[105, 256]),
    // ["hcl", "text"]
    "hcl" => TagSet::new(&[107, 256]),
    // ["c++", "header", "text"]
    "hh" => TagSet::new(&[31, 108, 256]),
    // ["hlsl", "text"]
    "hlsl" => TagSet::new(&[110, 256]),
    // ["hlsl", "text"]
    "hlsli" => TagSet::new(&[110, 256]),
    // ["c++", "header", "text"]
    "hpp" => TagSet::new(&[31, 108, 256]),
    // ["erlang", "text"]
    "hrl" => TagSet::new(&[73, 256]),
    // ["haskell", "text"]
    "hs" => TagSet::new(&[106, 256]),
    // ["html", "text"]
    "htm" => TagSet::new(&[111, 256]),
    // ["html", "text"]
    "html" => TagSet::new(&[111, 256]),
    // ["c++", "header", "text"]
    "hxx" => TagSet::new(&[31, 108, 256]),
    // ["binary", "icns"]
    "icns" => TagSet::new(&[21, 113]),
    // ["binary", "icon"]
    "ico" => TagSet::new(&[21, 114]),
    // ["icalendar", "text"]
    "ics" => TagSet::new(&[112, 256]),
    // ["idl", "text"]
    "idl" => TagSet::new(&[115, 256]),
    // ["idris", "text"]
    "idr" => TagSet::new(&[116, 256]),
    // ["inc", "text"]
    "inc" => TagSet::new(&[118, 256]),
    // ["ini", "text"]
    "ini" => TagSet::new(&[119, 256]),
    // ["c++", "inl", "text"]
    "inl" => TagSet::new(&[31, 120, 256]),
    // ["c++", "ino", "text"]
    "ino" => TagSet::new(&[31, 121, 256]),
    // ["inx", "text", "xml"]
    "inx" => TagSet::new(&[122, 256, 298]),
    // ["c++", "text"]
    "ipp" => TagSet::new(&[31, 256]),
    // ["ipxe", "text"]
    "ipxe" => TagSet::new(&[123, 256]),
    // ["json", "jupyter", "text"]
    "ipynb" => TagSet::new(&[135, 142, 256]),
    // ["c++", "text"]
    "ixx" => TagSet::new(&[31, 256]),
    // ["jinja", "text"]
    "j2" => TagSet::new(&[132, 256]),
    // ["jade", "text"]
    "jade" => TagSet::new(&[125, 256]),
    // ["binary", "jar", "zip"]
    "jar" => TagSet::new(&[21, 126, 309]),
    // ["java", "text"]
    "java" => TagSet::new(&[127, 256]),
    // ["jbuilder", "ruby", "text"]
    "jbuilder" => TagSet::new(&[130, 224, 256]),
    // ["groovy", "jenkins", "text"]
    "jenkins" => TagSet::new(&[101, 131, 256]),
    // ["groovy", "jenkins", "text"]
    "jenkinsfile" => TagSet::new(&[101, 131, 256]),
    // ["jinja", "text"]
    "jinja" => TagSet::new(&[132, 256]),
    // ["jinja", "text"]
    "jinja2" => TagSet::new(&[132, 256]),
    // ["julia", "text"]
    "jl" => TagSet::new(&[141, 256]),
    // ["binary", "image", "jpeg"]
    "jpeg" => TagSet::new(&[21, 117, 133]),
    // ["binary", "image", "jpeg"]
    "jpg" => TagSet::new(&[21, 117, 133]),
    // ["javascript", "text"]
    "js" => TagSet::new(&[129, 256]),
    // ["json", "text"]
    "json" => TagSet::new(&[135, 256]),
    // ["json5", "text"]
    "json5" => TagSet::new(&[136, 256]),
    // ["jsonc", "text"]
    "jsonc" => TagSet::new(&[137, 256]),
    // ["json", "jsonld", "text"]
    "jsonld" => TagSet::new(&[135, 138, 256]),
    // ["jsonnet", "text"]
    "jsonnet" => TagSet::new(&[139, 256]),
    // ["jsx", "text"]
    "jsx" => TagSet::new(&[140, 256]),
    // ["pem", "text"]
    "key" => TagSet::new(&[188, 256]),
    // ["kml", "text", "xml"]
    "kml" => TagSet::new(&[143, 256, 298]),
    // ["kotlin", "text"]
    "kt" => TagSet::new(&[144, 256]),
    // ["kotlin", "text"]
    "kts" => TagSet::new(&[144, 256]),
    // ["lean", "text"]
    "lean" => TagSet::new(&[148, 256]),
    // ["ini", "lektorproject", "text"]
    "lektorproject" => TagSet::new(&[119, 150, 256]),
    // ["less", "text"]
    "less" => TagSet::new(&[151, 256]),
    // ["lazarus", "lazarus-form", "text"]
    "lfm" => TagSet::new(&[146, 147, 256]),
    // ["literate-haskell", "text"]
    "lhs" => TagSet::new(&[153, 256]),
    // ["jsonnet", "text"]
    "libsonnet" => TagSet::new(&[139, 256]),
    // ["idris", "text"]
    "lidr" => TagSet::new(&[116, 256]),
    // ["liquid", "text"]
    "liquid" => TagSet::new(&[152, 256]),
    // ["lazarus", "text", "xml"]
    "lpi" => TagSet::new(&[146, 256, 298]),
    // ["lazarus", "pascal", "text"]
    "lpr" => TagSet::new(&[146, 185, 256]),
    // ["lektor", "text"]
    "lr" => TagSet::new(&[149, 256]),
    // ["lua", "text"]
    "lua" => TagSet::new(&[154, 256]),
    // ["objective-c", "text"]
    "m" => TagSet::new(&[180, 256]),
    // ["m4", "text"]
    "m4" => TagSet::new(&[155, 256]),
    // ["magik", "text"]
    "magik" => TagSet::new(&[156, 256]),
    // ["makefile", "text"]
    "make" => TagSet::new(&[158, 256]),
    // ["manifest", "text"]
    "manifest" => TagSet::new(&[159, 256]),
    // ["map", "text"]
    "map" => TagSet::new(&[160, 256]),
    // ["markdown", "text"]
    "markdown" => TagSet::new(&[161, 256]),
    // ["markdown", "text"]
    "md" => TagSet::new(&[161, 256]),
    // ["mdx", "text"]
    "mdx" => TagSet::new(&[162, 256]),
    // ["meson", "text"]
    "meson" => TagSet::new(&[164, 256]),
    // ["metal", "text"]
    "metal" => TagSet::new(&[166, 256]),
    // ["mib", "text"]
    "mib" => TagSet::new(&[167, 256]),
    // ["javascript", "text"]
    "mjs" => TagSet::new(&[129, 256]),
    // ["makefile", "text"]
    "mk" => TagSet::new(&[158, 256]),
    // ["ocaml", "text"]
    "ml" => TagSet::new(&[182, 256]),
    // ["ocaml", "text"]
    "mli" => TagSet::new(&[182, 256]),
    // ["c++", "objective-c++", "text"]
    "mm" => TagSet::new(&[31, 181, 256]),
    // ["modulemap", "text"]
    "modulemap" => TagSet::new(&[168, 256]),
    // ["musescore", "text", "xml"]
    "mscx" => TagSet::new(&[170, 256, 298]),
    // ["binary", "musescore", "zip"]
    "mscz" => TagSet::new(&[21, 170, 309]),
    // ["text", "ts"]
    "mts" => TagSet::new(&[256, 262]),
    // ["mustache", "text"]
    "mustache" => TagSet::new(&[171, 256]),
    // ["myst", "text"]
    "myst" => TagSet::new(&[172, 256]),
    // ["ngdoc", "text"]
    "ngdoc" => TagSet::new(&[173, 256]),
    // ["nim", "text"]
    "nim" => TagSet::new(&[174, 256]),
    // ["nimble", "text"]
    "nimble" => TagSet::new(&[175, 256]),
    // ["nim", "text"]
    "nims" => TagSet::new(&[174, 256]),
    // ["nix", "text"]
    "nix" => TagSet::new(&[176, 256]),
    // ["nunjucks", "text"]
    "njk" => TagSet::new(&[179, 256]),
    // ["binary", "otf"]
    "otf" => TagSet::new(&[21, 183]),
    // ["binary", "p12"]
    "p12" => TagSet::new(&[21, 184]),
    // ["pascal", "text"]
    "pas" => TagSet::new(&[185, 256]),
    // ["diff", "text"]
    "patch" => TagSet::new(&[57, 256]),
    // ["binary", "pdf"]
    "pdf" => TagSet::new(&[21, 187]),
    // ["pem", "text"]
    "pem" => TagSet::new(&[188, 256]),
    // ["php", "text"]
    "php" => TagSet::new(&[190, 256]),
    // ["php", "text"]
    "php4" => TagSet::new(&[190, 256]),
    // ["php", "text"]
    "php5" => TagSet::new(&[190, 256]),
    // ["php", "text"]
    "phtml" => TagSet::new(&[190, 256]),
    // ["json", "piskel", "text"]
    "piskel" => TagSet::new(&[135, 193, 256]),
    // ["perl", "text"]
    "pl" => TagSet::new(&[189, 256]),
    // ["plantuml", "text"]
    "plantuml" => TagSet::new(&[196, 256]),
    // ["plist"]
    "plist" => TagSet::new(&[197]),
    // ["perl", "text"]
    "pm" => TagSet::new(&[189, 256]),
    // ["binary", "image", "png"]
    "png" => TagSet::new(&[21, 117, 198]),
    // ["pofile", "text"]
    "po" => TagSet::new(&[199, 256]),
    // ["pom", "text", "xml"]
    "pom" => TagSet::new(&[200, 256, 298]),
    // ["puppet", "text"]
    "pp" => TagSet::new(&[207, 256]),
    // ["image", "ppm"]
    "ppm" => TagSet::new(&[117, 202]),
    // ["prisma", "text"]
    "prisma" => TagSet::new(&[204, 256]),
    // ["java-properties", "text"]
    "properties" => TagSet::new(&[128, 256]),
    // ["msbuild", "text", "xml"]
    "props" => TagSet::new(&[169, 256, 298]),
    // ["proto", "text"]
    "proto" => TagSet::new(&[205, 256]),
    // ["powershell", "text"]
    "ps1" => TagSet::new(&[201, 256]),
    // ["powershell", "text"]
    "psd1" => TagSet::new(&[201, 256]),
    // ["powershell", "text"]
    "psm1" => TagSet::new(&[201, 256]),
    // ["pug", "text"]
    "pug" => TagSet::new(&[206, 256]),
    // ["plantuml", "text"]
    "puml" => TagSet::new(&[196, 256]),
    // ["purescript", "text"]
    "purs" => TagSet::new(&[208, 256]),
    // ["cython", "text"]
    "pxd" => TagSet::new(&[52, 256]),
    // ["cython", "text"]
    "pxi" => TagSet::new(&[52, 256]),
    // ["python", "text"]
    "py" => TagSet::new(&[214, 256]),
    // ["pyi", "text"]
    "pyi" => TagSet::new(&[209, 256]),
    // ["msbuild", "pyproj", "text", "xml"]
    "pyproj" => TagSet::new(&[169, 212, 256, 298]),
    // ["python", "text"]
    "pyt" => TagSet::new(&[214, 256]),
    // ["python", "text"]
    "pyw" => TagSet::new(&[214, 256]),
    // ["cython", "text"]
    "pyx" => TagSet::new(&[52, 256]),
    // ["binary", "pyz"]
    "pyz" => TagSet::new(&[21, 217]),
    // ["binary", "pyz"]
    "pyzw" => TagSet::new(&[21, 217]),
    // ["qml", "text"]
    "qml" => TagSet::new(&[218, 256]),
    // ["r", "text"]
    "r" => TagSet::new(&[219, 256]),
    // ["ruby", "text"]
    "rake" => TagSet::new(&[224, 256]),
    // ["ruby", "text"]
    "rb" => TagSet::new(&[224, 256]),
    // ["resx", "text", "xml"]
    "resx" => TagSet::new(&[221, 256, 298]),
    // ["relax-ng", "text", "xml"]
    "rng" => TagSet::new(&[220, 256, 298]),
    // ["robot", "text"]
    "robot" => TagSet::new(&[222, 256]),
    // ["rust", "text"]
    "rs" => TagSet::new(&[225, 256]),
    // ["rst", "text"]
    "rst" => TagSet::new(&[223, 256]),
    // ["asm", "text"]
    "s" => TagSet::new(&[6, 256]),
    // ["sas", "text"]
    "sas" => TagSet::new(&[228, 256]),
    // ["sass", "text"]
    "sass" => TagSet::new(&[229, 256]),
    // ["sbt", "scala", "text"]
    "sbt" => TagSet::new(&[230, 231, 256]),
    // ["scala", "text"]
    "sc" => TagSet::new(&[231, 256]),
    // ["scala", "text"]
    "scala" => TagSet::new(&[231, 256]),
    // ["scheme", "text"]
    "scm" => TagSet::new(&[232, 256]),
    // ["scss", "text"]
    "scss" => TagSet::new(&[234, 256]),
    // ["shell", "text"]
    "sh" => TagSet::new(&[236, 256]),
    // ["sln", "text"]
    "sln" => TagSet::new(&[237, 256]),
    // ["msbuild", "slnx", "text", "xml"]
    "slnx" => TagSet::new(&[169, 238, 256, 298]),
    // ["salt", "text"]
    "sls" => TagSet::new(&[226, 256]),
    // ["binary"]
    "so" => TagSet::new(&[21]),
    // ["solidity", "text"]
    "sol" => TagSet::new(&[240, 256]),
    // ["spec", "text"]
    "spec" => TagSet::new(&[241, 256]),
    // ["sql", "text"]
    "sql" => TagSet::new(&[242, 256]),
    // ["scheme", "text"]
    "ss" => TagSet::new(&[232, 256]),
    // ["tex", "text"]
    "sty" => TagSet::new(&[255, 256]),
    // ["stylus", "text"]
    "styl" => TagSet::new(&[243, 256]),
    // ["system-verilog", "text"]
    "sv" => TagSet::new(&[250, 256]),
    // ["svelte", "text"]
    "svelte" => TagSet::new(&[244, 256]),
    // ["image", "svg", "text", "xml"]
    "svg" => TagSet::new(&[117, 245, 256, 298]),
    // ["system-verilog", "text"]
    "svh" => TagSet::new(&[250, 256]),
    // ["binary", "swf"]
    "swf" => TagSet::new(&[21, 246]),
    // ["swift", "text"]
    "swift" => TagSet::new(&[247, 256]),
    // ["swiftdeps", "text"]
    "swiftdeps" => TagSet::new(&[248, 256]),
    // ["python", "text", "twisted"]
    "tac" => TagSet::new(&[214, 256, 267]),
    // ["binary", "tar"]
    "tar" => TagSet::new(&[21, 251]),
    // ["msbuild", "text", "xml"]
    "targets" => TagSet::new(&[169, 256, 298]),
    // ["templ", "text"]
    "templ" => TagSet::new(&[253, 256]),
    // ["tex", "text"]
    "tex" => TagSet::new(&[255, 256]),
    // ["text", "textproto"]
    "textproto" => TagSet::new(&[256, 257]),
    // ["terraform", "text"]
    "tf" => TagSet::new(&[254, 256]),
    // ["terraform", "text"]
    "tfvars" => TagSet::new(&[254, 256]),
    // ["binary", "gzip"]
    "tgz" => TagSet::new(&[21, 104]),
    // ["text", "thrift"]
    "thrift" => TagSet::new(&[256, 258]),
    // ["binary", "image", "tiff"]
    "tif" => TagSet::new(&[21, 117, 259]),
    // ["binary", "image", "tiff"]
    "tiff" => TagSet::new(&[21, 117, 259]),
    // ["text", "toml"]
    "toml" => TagSet::new(&[256, 261]),
    // ["c++", "text"]
    "tpp" => TagSet::new(&[31, 256]),
    // ["text", "ts"]
    "ts" => TagSet::new(&[256, 262]),
    // ["text", "tsv"]
    "tsv" => TagSet::new(&[256, 263]),
    // ["text", "tsx"]
    "tsx" => TagSet::new(&[256, 264]),
    // ["binary", "ttf"]
    "ttf" => TagSet::new(&[21, 265]),
    // ["text", "twig"]
    "twig" => TagSet::new(&[256, 266]),
    // ["ini", "text", "txsprofile"]
    "txsprofile" => TagSet::new(&[119, 256, 268]),
    // ["plain-text", "text"]
    "txt" => TagSet::new(&[195, 256]),
    // ["text", "textproto"]
    "txtpb" => TagSet::new(&[256, 257]),
    // ["text", "urdf", "xml"]
    "urdf" => TagSet::new(&[256, 269, 298]),
    // ["text", "verilog"]
    "v" => TagSet::new(&[256, 274]),
    // ["text", "vb"]
    "vb" => TagSet::new(&[256, 270]),
    // ["msbuild", "text", "vbproj", "xml"]
    "vbproj" => TagSet::new(&[169, 256, 271, 298]),
    // ["msbuild", "text", "vcxproj", "xml"]
    "vcxproj" => TagSet::new(&[169, 256, 272, 298]),
    // ["text", "vdx"]
    "vdx" => TagSet::new(&[256, 273]),
    // ["text", "verilog"]
    "vh" => TagSet::new(&[256, 274]),
    // ["text", "vhdl"]
    "vhd" => TagSet::new(&[256, 275]),
    // ["text", "vim"]
    "vim" => TagSet::new(&[256, 276]),
    // ["text", "vtl"]
    "vtl" => TagSet::new(&[256, 277]),
    // ["text", "vue"]
    "vue" => TagSet::new(&[256, 278]),
    // ["binary", "jar", "zip"]
    "war" => TagSet::new(&[21, 126, 309]),
    // ["audio", "binary", "wav"]
    "wav" => TagSet::new(&[9, 21, 279]),
    // ["binary", "image", "webp"]
    "webp" => TagSet::new(&[21, 117, 280]),
    // ["binary", "wheel", "zip"]
    "whl" => TagSet::new(&[21, 281, 309]),
    // ["text", "wkt"]
    "wkt" => TagSet::new(&[256, 282]),
    // ["binary", "woff"]
    "woff" => TagSet::new(&[21, 283]),
    // ["binary", "woff2"]
    "woff2" => TagSet::new(&[21, 284]),
    // ["text", "wsdl", "xml"]
    "wsdl" => TagSet::new(&[256, 285, 298]),
    // ["python", "text", "wsgi"]
    "wsgi" => TagSet::new(&[214, 256, 286]),
    // ["text", "urdf", "xacro", "xml"]
    "xacro" => TagSet::new(&[256, 269, 287, 298]),
    // ["text", "xaml", "xml"]
    "xaml" => TagSet::new(&[256, 288, 298]),
    // ["text", "xcconfig", "xcodebuild"]
    "xcconfig" => TagSet::new(&[256, 289, 290]),
    // ["plist", "xcodebuild", "xcprivacy"]
    "xcprivacy" => TagSet::new(&[197, 290, 291]),
    // ["text", "xcodebuild", "xcscheme", "xml"]
    "xcscheme" => TagSet::new(&[256, 290, 292, 298]),
    // ["plist", "xcodebuild", "xcsettings"]
    "xcsettings" => TagSet::new(&[197, 290, 293]),
    // ["json", "text", "xcodebuild", "xctestplan"]
    "xctestplan" => TagSet::new(&[135, 256, 290, 294]),
    // ["text", "xcodebuild", "xcworkspacedata", "xml"]
    "xcworkspacedata" => TagSet::new(&[256, 290, 295, 298]),
    // ["html", "text", "xhtml", "xml"]
    "xhtml" => TagSet::new(&[111, 256, 296, 298]),
    // ["text", "xliff", "xml"]
    "xlf" => TagSet::new(&[256, 297, 298]),
    // ["text", "xliff", "xml"]
    "xliff" => TagSet::new(&[256, 297, 298]),
    // ["text", "xml"]
    "xml" => TagSet::new(&[256, 298]),
    // ["text", "xquery"]
    "xq" => TagSet::new(&[256, 299]),
    // ["text", "xquery"]
    "xql" => TagSet::new(&[256, 299]),
    // ["text", "xquery"]
    "xqm" => TagSet::new(&[256, 299]),
    // ["text", "xquery"]
    "xqu" => TagSet::new(&[256, 299]),
    // ["text", "xquery"]
    "xquery" => TagSet::new(&[256, 299]),
    // ["text", "xquery"]
    "xqy" => TagSet::new(&[256, 299]),
    // ["text", "xml", "xsd"]
    "xsd" => TagSet::new(&[256, 298, 300]),
    // ["text", "xml", "xsl"]
    "xsl" => TagSet::new(&[256, 298, 301]),
    // ["text", "xml", "xsl"]
    "xslt" => TagSet::new(&[256, 298, 301]),
    // ["text", "yaml"]
    "yaml" => TagSet::new(&[256, 302]),
    // ["text", "yaml", "yamlld"]
    "yamlld" => TagSet::new(&[256, 302, 303]),
    // ["text", "yang"]
    "yang" => TagSet::new(&[256, 305]),
    // ["text", "xml", "yin"]
    "yin" => TagSet::new(&[256, 298, 306]),
    // ["text", "yaml"]
    "yml" => TagSet::new(&[256, 302]),
    // ["text", "xml", "zcml"]
    "zcml" => TagSet::new(&[256, 298, 307]),
    // ["text", "zig"]
    "zig" => TagSet::new(&[256, 308]),
    // ["binary", "zip"]
    "zip" => TagSet::new(&[21, 309]),
    // ["text", "zpt"]
    "zpt" => TagSet::new(&[256, 310]),
    // ["shell", "text", "zsh"]
    "zsh" => TagSet::new(&[236, 256, 311]),
};

pub const NAMES: phf::Map<&str, TagSet> = phf::phf_map! {
    // ["text", "yaml"]
    ".ansible-lint" => TagSet::new(&[256, 302]),
    // ["babelrc", "json", "text"]
    ".babelrc" => TagSet::new(&[13, 135, 256]),
    // ["bash", "shell", "text"]
    ".bash_aliases" => TagSet::new(&[14, 236, 256]),
    // ["bash", "shell", "text"]
    ".bash_profile" => TagSet::new(&[14, 236, 256]),
    // ["bash", "shell", "text"]
    ".bashrc" => TagSet::new(&[14, 236, 256]),
    // ["bazelrc", "text"]
    ".bazelrc" => TagSet::new(&[18, 256]),
    // ["bowerrc", "json", "text"]
    ".bowerrc" => TagSet::new(&[24, 135, 256]),
    // ["browserslistrc", "text"]
    ".browserslistrc" => TagSet::new(&[25, 256]),
    // ["text", "yaml"]
    ".clang-format" => TagSet::new(&[256, 302]),
    // ["text", "yaml"]
    ".clang-tidy" => TagSet::new(&[256, 302]),
    // ["codespellrc", "ini", "text"]
    ".codespellrc" => TagSet::new(&[39, 119, 256]),
    // ["coveragerc", "ini", "text"]
    ".coveragerc" => TagSet::new(&[41, 119, 256]),
    // ["csh", "shell", "text"]
    ".cshrc" => TagSet::new(&[43, 236, 256]),
    // ["csslintrc", "json", "text"]
    ".csslintrc" => TagSet::new(&[47, 135, 256]),
    // ["dockerignore", "text"]
    ".dockerignore" => TagSet::new(&[60, 256]),
    // ["editorconfig", "text"]
    ".editorconfig" => TagSet::new(&[63, 256]),
    // ["bash", "shell", "text"]
    ".envrc" => TagSet::new(&[14, 236, 256]),
    // ["flake8", "ini", "text"]
    ".flake8" => TagSet::new(&[81, 119, 256]),
    // ["gitattributes", "text"]
    ".gitattributes" => TagSet::new(&[89, 256]),
    // ["gitconfig", "ini", "text"]
    ".gitconfig" => TagSet::new(&[90, 119, 256]),
    // ["gitignore", "text"]
    ".gitignore" => TagSet::new(&[91, 256]),
    // ["gitlint", "ini", "text"]
    ".gitlint" => TagSet::new(&[92, 119, 256]),
    // ["gitmodules", "text"]
    ".gitmodules" => TagSet::new(&[93, 256]),
    // ["hgrc", "ini", "text"]
    ".hgrc" => TagSet::new(&[109, 119, 256]),
    // ["ini", "isort", "text"]
    ".isort.cfg" => TagSet::new(&[119, 124, 256]),
    // ["jshintrc", "json", "text"]
    ".jshintrc" => TagSet::new(&[134, 135, 256]),
    // ["mailmap", "text"]
    ".mailmap" => TagSet::new(&[157, 256]),
    // ["json", "mention-bot", "text"]
    ".mention-bot" => TagSet::new(&[135, 163, 256]),
    // ["npmignore", "text"]
    ".npmignore" => TagSet::new(&[178, 256]),
    // ["pdbrc", "python", "text"]
    ".pdbrc" => TagSet::new(&[186, 214, 256]),
    // ["gitignore", "prettierignore", "text"]
    ".prettierignore" => TagSet::new(&[91, 203, 256]),
    // ["ini", "pypirc", "text"]
    ".pypirc" => TagSet::new(&[119, 211, 256]),
    // ["ini", "text"]
    ".rstcheck.cfg" => TagSet::new(&[119, 256]),
    // ["salt-lint", "text", "yaml"]
    ".salt-lint" => TagSet::new(&[227, 256, 302]),
    // ["ini", "text"]
    ".sqlfluff" => TagSet::new(&[119, 256]),
    // ["text", "yaml", "yamllint"]
    ".yamllint" => TagSet::new(&[256, 302, 304]),
    // ["shell", "text", "zsh"]
    ".zlogin" => TagSet::new(&[236, 256, 311]),
    // ["shell", "text", "zsh"]
    ".zlogout" => TagSet::new(&[236, 256, 311]),
    // ["shell", "text", "zsh"]
    ".zprofile" => TagSet::new(&[236, 256, 311]),
    // ["shell", "text", "zsh"]
    ".zshenv" => TagSet::new(&[236, 256, 311]),
    // ["shell", "text", "zsh"]
    ".zshrc" => TagSet::new(&[236, 256, 311]),
    // ["plain-text", "text"]
    "AUTHORS" => TagSet::new(&[195, 256]),
    // ["bazel", "text"]
    "BUILD" => TagSet::new(&[17, 256]),
    // ["ruby", "text"]
    "Brewfile" => TagSet::new(&[224, 256]),
    // ["plain-text", "text"]
    "CHANGELOG" => TagSet::new(&[195, 256]),
    // ["cmake", "text"]
    "CMakeLists.txt" => TagSet::new(&[38, 256]),
    // ["plain-text", "text"]
    "CONTRIBUTING" => TagSet::new(&[195, 256]),
    // ["plain-text", "text"]
    "COPYING" => TagSet::new(&[195, 256]),
    // ["cargo-lock", "text", "toml"]
    "Cargo.lock" => TagSet::new(&[34, 256, 261]),
    // ["cargo", "text", "toml"]
    "Cargo.toml" => TagSet::new(&[33, 256, 261]),
    // ["dockerfile", "text"]
    "Containerfile" => TagSet::new(&[59, 256]),
    // ["dockerfile", "text"]
    "Dockerfile" => TagSet::new(&[59, 256]),
    // ["ruby", "text"]
    "Fastfile" => TagSet::new(&[224, 256]),
    // ["makefile", "text"]
    "GNUmakefile" => TagSet::new(&[158, 256]),
    // ["ruby", "text"]
    "Gemfile" => TagSet::new(&[224, 256]),
    // ["text"]
    "Gemfile.lock" => TagSet::new(&[256]),
    // ["groovy", "jenkins", "text"]
    "Jenkinsfile" => TagSet::new(&[101, 131, 256]),
    // ["plain-text", "text"]
    "LICENSE" => TagSet::new(&[195, 256]),
    // ["plain-text", "text"]
    "MAINTAINERS" => TagSet::new(&[195, 256]),
    // ["makefile", "text"]
    "Makefile" => TagSet::new(&[158, 256]),
    // ["plain-text", "text"]
    "NEWS" => TagSet::new(&[195, 256]),
    // ["plain-text", "text"]
    "NOTICE" => TagSet::new(&[195, 256]),
    // ["plain-text", "text"]
    "PATENTS" => TagSet::new(&[195, 256]),
    // ["alpm", "bash", "pkgbuild", "shell", "text"]
    "PKGBUILD" => TagSet::new(&[1, 14, 194, 236, 256]),
    // ["text", "toml"]
    "Pipfile" => TagSet::new(&[256, 261]),
    // ["json", "text"]
    "Pipfile.lock" => TagSet::new(&[135, 256]),
    // ["plain-text", "text"]
    "README" => TagSet::new(&[195, 256]),
    // ["ruby", "text"]
    "Rakefile" => TagSet::new(&[224, 256]),
    // ["scons", "text"]
    "SConscript" => TagSet::new(&[233, 256]),
    // ["scons", "text"]
    "SConstruct" => TagSet::new(&[233, 256]),
    // ["scons", "text"]
    "SCsub" => TagSet::new(&[233, 256]),
    // ["text", "tiltfile"]
    "Tiltfile" => TagSet::new(&[256, 260]),
    // ["ruby", "text"]
    "Vagrantfile" => TagSet::new(&[224, 256]),
    // ["bazel", "text"]
    "WORKSPACE" => TagSet::new(&[17, 256]),
    // ["bitbake", "text"]
    "bblayers.conf" => TagSet::new(&[22, 256]),
    // ["bitbake", "text"]
    "bitbake.conf" => TagSet::new(&[22, 256]),
    // ["ruby", "text"]
    "config.ru" => TagSet::new(&[224, 256]),
    // ["bazel", "text"]
    "copy.bara.sky" => TagSet::new(&[17, 256]),
    // ["bash", "shell", "text"]
    "direnvrc" => TagSet::new(&[14, 236, 256]),
    // ["go-mod", "text"]
    "go.mod" => TagSet::new(&[96, 256]),
    // ["go-sum", "text"]
    "go.sum" => TagSet::new(&[97, 256]),
    // ["makefile", "text"]
    "makefile" => TagSet::new(&[158, 256]),
    // ["meson", "text"]
    "meson.build" => TagSet::new(&[164, 256]),
    // ["meson", "meson-options", "text"]
    "meson.options" => TagSet::new(&[164, 165, 256]),
    // ["meson", "meson-options", "text"]
    "meson_options.txt" => TagSet::new(&[164, 165, 256]),
    // ["text", "toml"]
    "poetry.lock" => TagSet::new(&[256, 261]),
    // ["pom", "text", "xml"]
    "pom.xml" => TagSet::new(&[200, 256, 298]),
    // ["ini", "pylintrc", "text"]
    "pylintrc" => TagSet::new(&[119, 210, 256]),
    // ["pyproject", "text", "toml"]
    "pyproject.toml" => TagSet::new(&[213, 256, 261]),
    // ["erlang", "text"]
    "rebar.config" => TagSet::new(&[73, 256]),
    // ["ini", "text"]
    "setup.cfg" => TagSet::new(&[119, 256]),
    // ["erlang", "text"]
    "sys.config" => TagSet::new(&[73, 256]),
    // ["erlang", "text"]
    "sys.config.src" => TagSet::new(&[73, 256]),
    // ["text", "toml"]
    "uv.lock" => TagSet::new(&[256, 261]),
    // ["python", "text"]
    "wscript" => TagSet::new(&[214, 256]),
};
