# This workflow comments on a PR with the results of the hyperfine benchmarks.
# This is a workaround for the limitations imposed by GitHub Actions on workflows triggered by pull requests from forked repositories.

# The restrictions apply to the pull_request event triggered by a fork opening a pull request in the upstream repository.
# - Events from forks cannot access secrets, except for the default GITHUB_TOKEN.
# - The GITHUB_TOKEN has read-only access when an event is triggered by a forked repository.
#
# These restrictions mean that during a pull_request event triggered by a forked repository,
# actions have no write access to GitHub resources and will fail on any attempt.
name: Hyperfine Comment
on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [hyperfine]
    types: [completed]
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: The hyperfine workflow run ID
        required: true

permissions: {}

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: hyperfine-results
          path: /tmp/hyperfine-results/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id || github.event.inputs.workflow_run_id }}

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          sparse-checkout: .github/scripts/hyperfine-comment.sh
          sparse-checkout-cone-mode: false

      - name: Comment on PR
        run: .github/scripts/hyperfine-comment.sh
